import { Request } from 'express';

// ─── User Roles ───────────────────────────────────────────────────────────────

/**
 * Enumeration of all roles available in the system.
 *
 * Keep this in sync with the `UserRole` enum in the Prisma schema.
 */
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  HR_MANAGER = 'HR_MANAGER',
  HR_SPECIALIST = 'HR_SPECIALIST',
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  RECRUITER = 'RECRUITER',
  READ_ONLY = 'READ_ONLY',
}

// ─── Authenticated User ───────────────────────────────────────────────────────

/**
 * AuthenticatedUser
 *
 * Shape of the user object attached to the request after successful
 * JWT verification by JwtStrategy. All fields are guaranteed to exist
 * when the user has been authenticated.
 */
export interface AuthenticatedUser {
  /** UUID of the user record in the database. */
  id: string;

  /** User's email address. */
  email: string;

  /** User's display name. */
  name: string;

  /** User's role in the system. Used by RolesGuard. */
  role: UserRole | string;

  /**
   * UUID of the tenant this user belongs to.
   * Null only for SUPER_ADMIN users who are not scoped to any tenant.
   */
  tenantId: string | null;

  /**
   * ISO timestamp of token issuance (from JWT `iat` claim).
   * Used to invalidate tokens issued before a password change.
   */
  issuedAt?: number;
}

// ─── Extended Express Request ─────────────────────────────────────────────────

/**
 * AuthenticatedRequest
 *
 * Extends the Express Request interface with fields added by NestJS
 * middleware, guards, and strategies throughout the request lifecycle.
 *
 * Import this instead of `Request` when working inside guards, interceptors,
 * or middleware that need access to auth/tenant context.
 */
export interface AuthenticatedRequest extends Request {
  /**
   * The authenticated user — populated by JwtStrategy after token verification.
   * `undefined` on unauthenticated routes.
   */
  user?: AuthenticatedUser;

  /**
   * The current tenant ID — populated by TenantMiddleware.
   * `null` when:
   *  - The request is on a public route that has not established a tenant context.
   *  - The user is SUPER_ADMIN making a cross-tenant request.
   */
  tenantId: string | null;

  /**
   * A unique identifier for this HTTP request, generated by TenantMiddleware.
   * Used for log correlation across the request lifecycle.
   * Format: UUID v4.
   */
  requestId: string;
}

// ─── Module Augmentation — Extend Express `Request` globally ─────────────────

/**
 * Augmenting the Express namespace ensures that TypeScript recognizes the
 * custom fields on `req` throughout the codebase without requiring explicit
 * casts everywhere.
 *
 * NestJS merges these types with the Express `Request` interface automatically.
 */
declare module 'express' {
  interface Request {
    user?: AuthenticatedUser;
    tenantId?: string | null;
    requestId?: string;
  }
}
