// @ts-nocheck
import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { v4 as uuidv4 } from 'uuid';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { PDFDocument, rgb } from 'pdf-lib';
import { Document, Packer, Paragraph, TextRun } from 'docx';

@Injectable()
export class DocumentService {
  private readonly logger = new Logger(DocumentService.name);
  private s3Client: S3Client;

  constructor(private prisma: PrismaService) {
    this.s3Client = new S3Client({
      region: 'us-east-1',
      endpoint: process.env.STORAGE_ENDPOINT || 'http://localhost:9000',
      credentials: {
        accessKeyId: process.env.STORAGE_ACCESS_KEY || 'minioadmin',
        secretAccessKey: process.env.STORAGE_SECRET_KEY || 'minioadmin_secret',
      },
      forcePathStyle: true, // Needed for MinIO
    });
  }

  async generateDocument(tenantId: string, userId: string, dto: any) {
    const bucket = 'hrmanager';
    const key = `tenant/${tenantId}/docs/${uuidv4()}.${dto.format || 'pdf'}`;
    let fileBuffer: Buffer | Uint8Array;

    try {
      if (dto.format === 'docx') {
        const doc = new Document({
          sections: [{
            properties: {},
            children: [
              new Paragraph({
                children: [
                  new TextRun(`Title: ${dto.title}`),
                  new TextRun({ text: `\n\nType: ${dto.type}`, break: 1 }),
                  new TextRun({ text: `\n\nGenerated by HRManager4U.ai Enterprise Document Engine.`, break: 1 }),
                ],
              }),
            ],
          }],
        });
        fileBuffer = await Packer.toBuffer(doc);
      } else {
        // PDF default
        const pdfDoc = await PDFDocument.create();
        const page = pdfDoc.addPage([600, 400]);
        page.drawText(`HRManager4U.ai\n\nTitle: ${dto.title}\nType: ${dto.type}\n\nGenerated Document.`, {
          x: 50,
          y: 300,
          size: 14,
          color: rgb(0, 0, 0),
        });
        fileBuffer = await pdfDoc.save();
      }

      // Upload to MinIO
      await this.s3Client.send(new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body: Buffer.from(fileBuffer),
        ContentType: dto.format === 'docx' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' : 'application/pdf',
      }));

    } catch (e) {
      this.logger.error('Failed to generate or upload document', e);
      throw new Error('Document generation failed');
    }

    const docRecord = await this.prisma.document.create({
      data: {
        tenantId,
        companyId: dto.companyId,
        type: dto.type,
        title: dto.title,
        description: dto.description || '',
        templateData: dto.templateData || {},
        status: 'GENERATED',
        pdfUrl: `${process.env.STORAGE_PUBLIC_URL || 'http://localhost:9000'}/${bucket}/${key}`,
        generatedBy: userId,
      },
    });

    return docRecord;
  }

  async findAll(tenantId: string, options: any) {
    const page = parseInt(options.page, 10) || 1;
    const limit = parseInt(options.limit, 10) || 10;
    const skip = (page - 1) * limit;
    const [data, total] = await Promise.all([
      this.prisma.document.findMany({
        where: { tenantId },
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.document.count({ where: { tenantId } }),
    ]);
    return { data, meta: { total, page, limit } };
  }

  async findOne(tenantId: string, id: string) {
    const document = await this.prisma.document.findFirst({
      where: { id, tenantId },
    });
    if (!document) throw new NotFoundException('Document not found');
    return document;
  }
}
